# Generated by Django 4.2.3 on 2023-07-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='admin_remark',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='status',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
