# Generated by Django 4.2.3 on 2023-07-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_volunteer_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='reg_date',
            field=models.DateTimeField(null=True),
        ),
    ]
