# Generated by Django 4.2.3 on 2023-07-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_volunteer_reg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='reg_date',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='user_pic',
        ),
    ]
