# Generated by Django 4.2.3 on 2023-07-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_volunteer_reg_date_remove_volunteer_user_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='reg_date',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user_pic',
        ),
    ]
