# Generated by Django 4.2.3 on 2023-07-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_staff_reg_date_remove_staff_user_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='reg_date',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='user_pic',
        ),
    ]
