# Generated by Django 4.2.3 on 2023-07-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_donor_reg_date_remove_donor_user_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_otp', models.IntegerField()),
                ('volunteer_otp', models.IntegerField()),
                ('donator_otp', models.IntegerField()),
                ('staff_otp', models.IntegerField()),
            ],
        ),
    ]
