# Generated by Django 4.2.3 on 2023-07-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='donator_otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='ngo_otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='staff_otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='volunteer_otp',
            field=models.IntegerField(null=True),
        ),
    ]
