# Generated by Django 4.2.3 on 2023-07-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_otp_donator_otp_alter_otp_ngo_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Otp',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
