# Generated by Django 4.2.3 on 2023-07-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='donator_otp',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='ngo_otp',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='staff_otp',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='volunteer_otp',
        ),
        migrations.AddField(
            model_name='otp',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
