# Generated by Django 4.2.3 on 2023-07-21 04:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_otp_donator_otp_remove_otp_ngo_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2023, 7, 21, 9, 45, 36, 730649))),
                ('end_date', models.DateTimeField(default=None)),
                ('associated_volunteers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('start_date', models.DateField(default=datetime.datetime(2023, 7, 21, 9, 45, 36, 731649))),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 7, 21, 9, 45, 36, 731649))),
                ('location', models.CharField(max_length=200)),
                ('associated_volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcoming_donation', models.CharField(max_length=200)),
                ('donation_amount', models.IntegerField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donor')),
            ],
        ),
    ]
