# Generated by Django 4.2.3 on 2023-07-21 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_project_event_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 21, 10, 8, 46, 678251)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 10, 8, 46, 678251)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 10, 8, 46, 677251)),
        ),
    ]
