# Generated by Django 4.2.3 on 2023-07-24 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_event_start_date_alter_event_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='donation',
            name='name',
            field=models.TextField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='name',
            field=models.TextField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.TextField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='name',
            field=models.TextField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 11, 44, 55, 195628)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 11, 44, 55, 195628)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 11, 44, 55, 195628)),
        ),
    ]
