# Generated by Django 4.2.3 on 2023-07-24 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_volunteer_options_donation_name_donor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 11, 49, 2, 333632)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 11, 49, 2, 333632)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 11, 49, 2, 332633)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.TextField(max_length=20),
        ),
    ]
