# Generated by Django 4.2.3 on 2023-07-24 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_donation_name_alter_donation_upcoming_donation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='about_donation',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 15, 5, 33, 555727)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 15, 5, 33, 555727)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 15, 5, 33, 554727)),
        ),
    ]
